In [2]:
pip install pyspark

Requirement already satisfied: pyspark in c:\users\surya.mahesh\appdata\local\anaconda3\lib\site-packages (3.5.2)
Requirement already satisfied: py4j==0.10.9.7 in c:\users\surya.mahesh\appdata\local\anaconda3\lib\site-packages (from pyspark) (0.10.9.7)
Note: you may need to restart the kernel to use updated packages.

In [3]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, concat_ws, split

In [4]:
SparkSession

pyspark.sql.session.SparkSession

In [5]:
spark = SparkSession.builder.appName('Youtube_Data_Analysis').getOrCreate()

In [6]:
spark

In [7]:
spark.sparkContext

In [8]:
from pyspark.sql.types import StructType,StructField,StringType,IntegerType
from pyspark.sql.functions import *

In [30]:
# Load the CSV file without headers
# Read the CSV file with space separator
df = spark.read.csv('youtubedata.csv',header=False,inferSchema=True)
df.toPandas()

,_c0,_c1,_c2,_c3,_c4,_c5,_c6,_c7,_c8,_c9,...,_c13,_c14,_c15,_c16,_c17,_c18,_c19,_c20,_c21,_c22
0,QuRYeRnAuXM,EvilSquirrelPictures,1135.0,Pets & Animals,252.0,1075.0,4.96,46.0,86.0,gFa1YMEJFag,...,0TZqX5MbXMA,UEvVksP91kg,ZTopArY7Nbg,0RViGi2Rne8,HT_QlOJbDpg,YZev1imoxX8,8qQrrfUTmh0,zQ83d_D2MGs,u6_DQQjLsAw,73Wz9CQFDtE
1,3TYqkBJ9YRk,hggh22,1135.0,Comedy,169.0,228.0,5.00,5.0,3.0,QuRYeRnAuXM,...,nRcovJn9xHg,sVkuOk4jmCo,ZTopArY7Nbg,HT_QlOJbDpg,0RViGi2Rne8,ShhClb6J-NA,g9e1alirMhc,YZev1imoxX8,I4yKEK9o8gA,zQ83d_D2MGs
2,rSJ8QZWBegU,TimeGem,1135.0,Entertainment,95.0,356.0,4.31,13.0,1.0,QuRYeRnAuXM,...,nRcovJn9xHg,sVkuOk4jmCo,ZTopArY7Nbg,gBcu22Vv1nY,HT_QlOJbDpg,0RViGi2Rne8,ShhClb6J-NA,g9e1alirMhc,YZev1imoxX8,I4yKEK9o8gA
3,nRcovJn9xHg,wooochacha,1135.0,Entertainment,118.0,1115.0,2.23,57.0,73.0,QuRYeRnAuXM,...,ZTopArY7Nbg,gBcu22Vv1nY,HT_QlOJbDpg,0RViGi2Rne8,ShhClb6J-NA,g9e1alirMhc,YZev1imoxX8,I4yKEK9o8gA,zQ83d_D2MGs,1GKaVzNDbuI
4,UEvVksP91kg,johnx113,1135.0,Entertainment,83.0,281.0,2.67,9.0,16.0,gFa1YMEJFag,...,rSJ8QZWBegU,nRcovJn9xHg,sVkuOk4jmCo,ZTopArY7Nbg,HT_QlOJbDpg,0RViGi2Rne8,g9e1alirMhc,YZev1imoxX8,I4yKEK9o8gA,zQ83d_D2MGs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4095,esCvu46qDaA,RSMFD,863.0,Entertainment,63.0,116929.0,4.84,182.0,222.0,8t4m5JM5r6Y,...,bhLbFGVduTA,tJGDW674hVo,TecLbWk8A3w,3Yb5YTEVlEo,e4yx1s-l6f8,yB62b8S3Ra4,2GHiAEeFQs0,pxcDZ9AohLM,G8OlUZEnyOA,M80K51DosFo
4096,kOZ8bRAO7YQ,RockstarGames,0.0,UNA,63.0,199361.0,4.79,1256.0,2410.0,None,...,None,None,None,None,None,None,None,None,None,None
4097,GSsVZcKHues,GTASite,1024.0,Entertainment,123.0,486752.0,4.86,1098.0,1764.0,TecLbWk8A3w,...,5-reBn0gUkg,PHLmbD_dLh4,bhLbFGVduTA,zwp3HEwA1oM,XjR5e2W8n8E,ka8xZhlMvps,pP3oC2pf_EU,YDgd4V0ILNw,q3qdBVDZrmE,hKSk1bW9qzw
4098,foKRqJGcbPQ,scrambledeggsTV,1100.0,Entertainment,136.0,13115.0,4.45,33.0,37.0,LzI9VyIjpDI,...,e4yx1s-l6f8,hKSk1bW9qzw,WWdESkWpKvI,2GHiAEeFQs0,GSsVZcKHues,q3qdBVDZrmE,IbEW4N3DmI0,odXW0Uaj8aU,z84ko4Xzn40,Qjj_uMubxP0
4099,-CYhSNHbeC8,rehab07,771.0,Entertainment,186.0,103556.0,4.30,277.0,220.0,wtVeF5bT6YQ,...,e4yx1s-l6f8,47EWHY3E5AM,uWIXSr5H_SI,cRqUsvTsbho,TecLbWk8A3w,yB62b8S3Ra4,27q5bD9e_ew,F5m4wyZxLq4,0n1plrwQwrk,GZ_ct8ad-dY

In [31]:
# Define the column names
column_names = [
    "Video ID", 
    "Video Uploader", 
    "Interval between YouTube Establishment and Video Upload",
    "Video Category", 
    "Video Length", 
    "Number of Views", 
    "Rating on the Video", 
    "Number of Ratings", 
    "Number of Comments", 
    "Related Video IDs"
]


# Rename the first 9 columns using the provided names
for i in range(len(column_names)):
    df = df.withColumnRenamed(f"_c{i}", column_names[i])

In [32]:
df.show()

+-----------+--------------------+-------------------------------------------------------+----------------+------------+---------------+-------------------+-----------------+------------------+-----------------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+
|   Video ID|      Video Uploader|Interval between YouTube Establishment and Video Upload|  Video Category|Video Length|Number of Views|Rating on the Video|Number of Ratings|Number of Comments|Related Video IDs|       _c10|       _c11|       _c12|       _c13|       _c14|       _c15|       _c16|       _c17|       _c18|       _c19|       _c20|       _c21|       _c22|
+-----------+--------------------+-------------------------------------------------------+----------------+------------+---------------+-------------------+-----------------+------------------+-----------------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+
|QuRYeRnAuXM|EvilSquirrelPictures|                                                 1135.0|  Pets & Animals|         252|           1075|               4.96|               46|                86|      gFa1YMEJFag|nRcovJn9xHg|3TYqkBJ9YRk|rSJ8QZWBegU|0TZqX5MbXMA|UEvVksP91kg|ZTopArY7Nbg|0RViGi2Rne8|HT_QlOJbDpg|YZev1imoxX8|8qQrrfUTmh0|zQ83d_D2MGs|u6_DQQjLsAw|73Wz9CQFDtE|
|3TYqkBJ9YRk|              hggh22|                                                 1135.0|          Comedy|         169|            228|                5.0|                5|                 3|      QuRYeRnAuXM|gFa1YMEJFag|UEvVksP91kg|rSJ8QZWBegU|nRcovJn9xHg|sVkuOk4jmCo|ZTopArY7Nbg|HT_QlOJbDpg|0RViGi2Rne8|ShhClb6J-NA|g9e1alirMhc|YZev1imoxX8|I4yKEK9o8gA|zQ83d_D2MGs|
|rSJ8QZWBegU|             TimeGem|                                                 1135.0|   Entertainment|          95|            356|               4.31|               13|                 1|      QuRYeRnAuXM|gFa1YMEJFag|UEvVksP91kg|3TYqkBJ9YRk|nRcovJn9xHg|sVkuOk4jmCo|ZTopArY7Nbg|gBcu22Vv1nY|HT_QlOJbDpg|0RViGi2Rne8|ShhClb6J-NA|g9e1alirMhc|YZev1imoxX8|I4yKEK9o8gA|
|nRcovJn9xHg|          wooochacha|                                                 1135.0|   Entertainment|         118|           1115|               2.23|               57|                73|      QuRYeRnAuXM|gFa1YMEJFag|UEvVksP91kg|3TYqkBJ9YRk|ZTopArY7Nbg|gBcu22Vv1nY|HT_QlOJbDpg|0RViGi2Rne8|ShhClb6J-NA|g9e1alirMhc|YZev1imoxX8|I4yKEK9o8gA|zQ83d_D2MGs|1GKaVzNDbuI|
|UEvVksP91kg|            johnx113|                                                 1135.0|   Entertainment|          83|            281|               2.67|                9|                16|      gFa1YMEJFag|QuRYeRnAuXM|3TYqkBJ9YRk|0TZqX5MbXMA|rSJ8QZWBegU|nRcovJn9xHg|sVkuOk4jmCo|ZTopArY7Nbg|HT_QlOJbDpg|0RViGi2Rne8|g9e1alirMhc|YZev1imoxX8|I4yKEK9o8gA|zQ83d_D2MGs|
|sVkuOk4jmCo|       marcosoycadiz|                                                 1135.0|  People & Blogs|          49|           1196|               3.67|                6|                 5|      yjt5v88-6Aw|sLrWjhvCoW8|dergWtU1tnE|Cs3TbaYxg_A|OOHsD-akNw0|9Vajm_u9TsI|ZW62z2-QfpA|4ki_fVDDlzs|WJ2WTPtijSc|8TknA5BqRBc|M2fcueuny7s|8Wd6y3Pb2yA|0aKz7qdtMj0|x50W-TW6yGg|
|ZTopArY7Nbg|         TroyChannel|                                                 1136.0|   Entertainment|         145|             11|                0.0|                0|                 0|      THM3FYUNyr8|pQPhV1mzh-g|NeIGddkjxJI|8-vZvDjh_3g|N6RuQAW1ALc|Dc_MIs3NzIQ|LsSendGJARs|MHADThckgkE|OTJGrqVOubA|BjU-c_aBXtc|dT1Hmv_2Qg8|apqOIWiKaXc|vX0vqQuXI9g|Gb7ztQ-baqo|
|0RViGi2Rne8|        OmnipotentSI|                                                 1135.0|   Entertainment|           9|            490|               2.31|               26|                15|      rSJ8QZWBegU|nRcovJn9xHg|0TZqX5MbXMA|UEvVksP91kg|gFa1YMEJFag|QuRYeRnAuXM|3TYqkBJ9YRk|HT_QlOJbDpg|ZTopArY7Nbg|g9e1alirMhc|YZev1imoxX8|I4yKEK9o8gA|zQ83d_D2MGs|1GKaVzNDbuI|
|HT_QlOJbDpg|   dumbasstheredneck|                                                 1095.0|          Comedy|          14|           1349|               2.09|               22|                13|      cdbp6rCVzRs|jVxz9wKEa3A|mUoRI-VnV6w|bGRB0Pwx_iM|B09qqpGr4Xo|6Xdg_elOGaY|8-7axRRXpfE|VO_mUdKmyds|1vGH08qoclk|eP94rcWKMNM|jFGu4xEvWUc|e7SnPCWPFxE|G_my4iaIYIM|e9y0_BgZU7g|
|ShhClb6J-NA|         thecrashguy|                                                 1136.0|   Entertainment|          61|             29|                0.0|                0|                 0|      8dEezTw8J_o|6DK-CJh6hTY|SArJyLS6T_Y|boRch04lh0I|yop2Ipym-ls|Ydnc_c4Afj0|HFaCubSrqdQ|tpUcCvJ9cio|8MrfxlBkHMQ|_CNGEzIuf_I|bKOzgNvNgTE|JJtHjzlBigU|fGkPWRrOTXA|oBqH_5mPxsc|
|g9e1alirMhc|      iamdanielisaac|                                                  541.0|          Comedy|         152|         483053|               4.65|             2689|              2932|      _i6OD_y_-AI|1GKaVzNDbuI|Bd61LnxqSng|97cWs8tW8mY|I4yKEK9o8gA|IBqQWAjBgmE|myQpL8_M980|WWqed9u6rr4|-mQH9DloKD8|2l6vwAIAqNU|E3XaD3Yu3qA|pFUYi7dp1WU|Dto7-3aOt8w|hiSmlmXp-aU|
|YZev1imoxX8|     threefirstnames|                                                 1135.0|   Entertainment|         253|             63|                5.0|                3|                 2|      ldZPDf2cwqI|-UvVtpmh4EQ|BzwpvskqHa4|OJtAoLrGA8Q|q5QOvQ8ZYUQ|MFmMssHR0Rc|vDuIB8Gv9GQ|3kITDVTeo-c|Dt5X1_3S_kM|P2OguaWyfzQ|vOAYUoiPkzA|_6ruNbrssO4|sSUu4ROj3FQ|n5Ngq0mKKzA|
|I4yKEK9o8gA|           djlogitek|                                                  964.0| News & Politics|         173|         106929|               4.39|             1010|              1484|      g9e1alirMhc|1GKaVzNDbuI|qCUYgddlvRM|J0Qu6eyyr4c|8n-nT-luFIw|q8XToX7aSdg|dzUNvEfYDEQ|WWqed9u6rr4|2l6vwAIAqNU|VWYX-LiQggc|gMuxyRbNLFM|IBqQWAjBgmE|JZekosYOmXc|DomumdGQSg8|
|1GKaVzNDbuI|             fatvids|                                                  690.0|          Comedy|         176|        2464486|                4.5|            13342|             11997|      Bd61LnxqSng|g9e1alirMhc|UrNqx1p95qs|sEJLOmVOpcU|WGV4u6GhGhw|Dto7-3aOt8w|I4yKEK9o8gA|p9CypIsNSvM|qJXYN3wFhgo|Vqiw-Kqtlr0|bnuaPr4hlCU|CKjha-rohzc|hSlo0T0CNI4|_i6OD_y_-AI|
|yuZhwV24PmM|          weneedhelp|                                                 1082.0| News & Politics|         213|          46183|               4.71|              280|               247|      hU9iCANi02o|xq8aopATYyw|g9e1alirMhc|I4yKEK9o8gA|HuTqgqhxVMc|QoMCoMMgeO0|6h3G-lMZxjo|b4LuFQJmS1Y|7ZVpPGxuafA|bfZ_gXCHaMw|1GKaVzNDbuI|9Fr1dm2Qdls|WWqed9u6rr4|L3gQfz8GC0o|
|zQ83d_D2MGs|   dumbasstheredneck|                                                 1095.0|          Comedy|          14|           1550|               1.57|               14|                 4|      HT_QlOJbDpg|cdbp6rCVzRs|gAHZ7DRyIgY|mUoRI-VnV6w|jFGu4xEvWUc|TEPH9ScDy1E|AK9_-sLF5M0|6Xdg_elOGaY|p4NVl4W6FHM|mCLw4iGZ7Ms|bGRB0Pwx_iM|ifTbWQW0w64|tPi04TrYskw|n00wAO4hg-U|
|DomumdGQSg8|           imgrown18|                                                  910.0|          Comedy|         224|         392908|                4.8|             1261|               829|      lVTS0iuo1EY|eOIFF_5ORGo|n7rlp3SLtus|u_9vYy-TCCk|kpq0zL-oW4M|J5z4Vs26-TI|b-iTzU_ZD4k|CvCqT9hkZiA|s5CqcdpwEq8|pvVo1290j1w|6g0XGKuC-ek|7TXjtbl2y3U|hpsra8ojBHQ|pqhlG9qYsR8|
|pFUYi7dp1WU|      StanleyJenkins|                                                 1106.0|          Comedy|         200|         110272|               4.07|             1011|               482|      _1haYY5pV18|ue5lVJuNlzQ|AkjUOT67hcU|Xw6xEYeUfj4|5e5tKtCoBfY|ZNfFc4-gV38|T4X8uj_SYPQ|IgVHe9CDQnU|l7Z818lnTK0|1piuJzS7H-4|1OErkBJ8Ha4|5MOriOpcgeQ|J5z4Vs26-TI|LpGZWsCapX4|
|2l6vwAIAqNU|        makemagazine|                                                  460.0|Film & Animation|         294|          71966|               4.07|              260|               229|      g9e1alirMhc|hiSmlmXp-aU|I4yKEK9o8gA|EGzHBtoVvpc|-mQH9DloKD8|IBqQWAjBgmE|LY0-Ya2YEoE|voQACEw_9EE|IiDQwQQsrL8|DomumdGQSg8|97cWs8tW8mY|NVOFmu2ZIqI|NfOPi0QO0FQ|gqHPYTUTToc|
|hiSmlmXp-aU|       bravenewfilms|                                                  440.0|   Entertainment|         168|         653840|               4.43|              198|               377|      ED6YaRl93CE|IBqQWAjBgmE|EGzHBtoVvpc|2l6vwAIAqNU|g9e1alirMhc|-mQH9DloKD8|I4yKEK9o8gA|1GKaVzNDbuI|wnDATe6MPrg|WWqed9u6rr4|97cWs8tW8mY|q65SsORdRO8|DomumdGQSg8|0GXjcE4gy7g|
+-----------+--------------------+-------------------------------------------------------+----------------+------------+---------------+-------------------+-----------------+------------------+-----------------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+
only showing top 20 rows

In [33]:
from pyspark.sql.functions import concat_ws, col

# Columns to combine: from _c10 to _c22
columns_to_combine = [col(f'_c{i}') for i in range(10, 23)]

# Combine all relevant columns into a single column called "Related Video IDs"
df = df.withColumn("Related Video IDs", concat_ws(" ", *columns_to_combine))

# Drop the original _c10 to _c22 columns
columns_to_drop = [f'_c{i}' for i in range(10, 23)]
df = df.drop(*columns_to_drop)

In [34]:

# Show the result
df.show()

+-----------+--------------------+-------------------------------------------------------+----------------+------------+---------------+-------------------+-----------------+------------------+--------------------+
|   Video ID|      Video Uploader|Interval between YouTube Establishment and Video Upload|  Video Category|Video Length|Number of Views|Rating on the Video|Number of Ratings|Number of Comments|   Related Video IDs|
+-----------+--------------------+-------------------------------------------------------+----------------+------------+---------------+-------------------+-----------------+------------------+--------------------+
|QuRYeRnAuXM|EvilSquirrelPictures|                                                 1135.0|  Pets & Animals|         252|           1075|               4.96|               46|                86|nRcovJn9xHg 3TYqk...|
|3TYqkBJ9YRk|              hggh22|                                                 1135.0|          Comedy|         169|            228|                5.0|                5|                 3|gFa1YMEJFag UEvVk...|
|rSJ8QZWBegU|             TimeGem|                                                 1135.0|   Entertainment|          95|            356|               4.31|               13|                 1|gFa1YMEJFag UEvVk...|
|nRcovJn9xHg|          wooochacha|                                                 1135.0|   Entertainment|         118|           1115|               2.23|               57|                73|gFa1YMEJFag UEvVk...|
|UEvVksP91kg|            johnx113|                                                 1135.0|   Entertainment|          83|            281|               2.67|                9|                16|QuRYeRnAuXM 3TYqk...|
|sVkuOk4jmCo|       marcosoycadiz|                                                 1135.0|  People & Blogs|          49|           1196|               3.67|                6|                 5|sLrWjhvCoW8 dergW...|
|ZTopArY7Nbg|         TroyChannel|                                                 1136.0|   Entertainment|         145|             11|                0.0|                0|                 0|pQPhV1mzh-g NeIGd...|
|0RViGi2Rne8|        OmnipotentSI|                                                 1135.0|   Entertainment|           9|            490|               2.31|               26|                15|nRcovJn9xHg 0TZqX...|
|HT_QlOJbDpg|   dumbasstheredneck|                                                 1095.0|          Comedy|          14|           1349|               2.09|               22|                13|jVxz9wKEa3A mUoRI...|
|ShhClb6J-NA|         thecrashguy|                                                 1136.0|   Entertainment|          61|             29|                0.0|                0|                 0|6DK-CJh6hTY SArJy...|
|g9e1alirMhc|      iamdanielisaac|                                                  541.0|          Comedy|         152|         483053|               4.65|             2689|              2932|1GKaVzNDbuI Bd61L...|
|YZev1imoxX8|     threefirstnames|                                                 1135.0|   Entertainment|         253|             63|                5.0|                3|                 2|-UvVtpmh4EQ Bzwpv...|
|I4yKEK9o8gA|           djlogitek|                                                  964.0| News & Politics|         173|         106929|               4.39|             1010|              1484|1GKaVzNDbuI qCUYg...|
|1GKaVzNDbuI|             fatvids|                                                  690.0|          Comedy|         176|        2464486|                4.5|            13342|             11997|g9e1alirMhc UrNqx...|
|yuZhwV24PmM|          weneedhelp|                                                 1082.0| News & Politics|         213|          46183|               4.71|              280|               247|xq8aopATYyw g9e1a...|
|zQ83d_D2MGs|   dumbasstheredneck|                                                 1095.0|          Comedy|          14|           1550|               1.57|               14|                 4|cdbp6rCVzRs gAHZ7...|
|DomumdGQSg8|           imgrown18|                                                  910.0|          Comedy|         224|         392908|                4.8|             1261|               829|eOIFF_5ORGo n7rlp...|
|pFUYi7dp1WU|      StanleyJenkins|                                                 1106.0|          Comedy|         200|         110272|               4.07|             1011|               482|ue5lVJuNlzQ AkjUO...|
|2l6vwAIAqNU|        makemagazine|                                                  460.0|Film & Animation|         294|          71966|               4.07|              260|               229|hiSmlmXp-aU I4yKE...|
|hiSmlmXp-aU|       bravenewfilms|                                                  440.0|   Entertainment|         168|         653840|               4.43|              198|               377|IBqQWAjBgmE EGzHB...|
+-----------+--------------------+-------------------------------------------------------+----------------+------------+---------------+-------------------+-----------------+------------------+--------------------+
only showing top 20 rows

In [35]:

from pyspark.sql.functions import col, regexp_replace

# Replace spaces with commas in the 'final_column' column
df = df.withColumn('Related Video IDs', regexp_replace(col('Related Video IDs'), ' ', ','))

In [36]:
df.toPandas()

,Video ID,Video Uploader,Interval between YouTube Establishment and Video Upload,Video Category,Video Length,Number of Views,Rating on the Video,Number of Ratings,Number of Comments,Related Video IDs
0,QuRYeRnAuXM,EvilSquirrelPictures,1135.0,Pets & Animals,252.0,1075.0,4.96,46.0,86.0,"nRcovJn9xHg,3TYqkBJ9YRk,rSJ8QZWBegU,0TZqX5MbXM..."
1,3TYqkBJ9YRk,hggh22,1135.0,Comedy,169.0,228.0,5.00,5.0,3.0,"gFa1YMEJFag,UEvVksP91kg,rSJ8QZWBegU,nRcovJn9xH..."
2,rSJ8QZWBegU,TimeGem,1135.0,Entertainment,95.0,356.0,4.31,13.0,1.0,"gFa1YMEJFag,UEvVksP91kg,3TYqkBJ9YRk,nRcovJn9xH..."
3,nRcovJn9xHg,wooochacha,1135.0,Entertainment,118.0,1115.0,2.23,57.0,73.0,"gFa1YMEJFag,UEvVksP91kg,3TYqkBJ9YRk,ZTopArY7Nb..."
4,UEvVksP91kg,johnx113,1135.0,Entertainment,83.0,281.0,2.67,9.0,16.0,"QuRYeRnAuXM,3TYqkBJ9YRk,0TZqX5MbXMA,rSJ8QZWBeg..."
...,...,...,...,...,...,...,...,...,...,...
4095,esCvu46qDaA,RSMFD,863.0,Entertainment,63.0,116929.0,4.84,182.0,222.0,"vOskZNJJII8,q3qdBVDZrmE,mLDLe024T_I,bhLbFGVduT..."
4096,kOZ8bRAO7YQ,RockstarGames,0.0,UNA,63.0,199361.0,4.79,1256.0,2410.0,
4097,GSsVZcKHues,GTASite,1024.0,Entertainment,123.0,486752.0,4.86,1098.0,1764.0,"vOskZNJJII8,_X5nHLOiAVo,cNION6wGuso,5-reBn0gUk..."
4098,foKRqJGcbPQ,scrambledeggsTV,1100.0,Entertainment,136.0,13115.0,4.45,33.0,37.0,"_X5nHLOiAVo,5-reBn0gUkg,e8bEzU2Tx7c,e4yx1s-l6f..."
4099,-CYhSNHbeC8,rehab07,771.0,Entertainment,186.0,103556.0,4.30,277.0,220.0,"EOj-iWkcJPU,pg3j4IBMRZE,2GHiAEeFQs0,e4yx1s-l6f..."

In [75]:
df.count()

4066

In [38]:
# Drop Null Values

In [73]:
df_cleaned=df.dropna(how="any")

In [74]:
df_cleaned.count()

4066

In [47]:
df_cleaned.printSchema()

root
 |-- Video ID: string (nullable = true)
 |-- Video Uploader: string (nullable = true)
 |-- Interval between YouTube Establishment and Video Upload: double (nullable = true)
 |-- Video Category: string (nullable = true)
 |-- Video Length: integer (nullable = true)
 |-- Number of Views: integer (nullable = true)
 |-- Rating on the Video: double (nullable = true)
 |-- Number of Ratings: integer (nullable = true)
 |-- Number of Comments: integer (nullable = true)
 |-- Related Video IDs: string (nullable = false)

In [76]:
data=df_cleaned

In [77]:
data.count()

4066

In [78]:
data.toPandas()

,Video ID,Video Uploader,Interval between YouTube Establishment and Video Upload,Video Category,Video Length,Number of Views,Rating on the Video,Number of Ratings,Number of Comments,Related Video IDs
0,QuRYeRnAuXM,EvilSquirrelPictures,1135.0,Pets & Animals,252,1075,4.96,46,86,"nRcovJn9xHg,3TYqkBJ9YRk,rSJ8QZWBegU,0TZqX5MbXM..."
1,3TYqkBJ9YRk,hggh22,1135.0,Comedy,169,228,5.00,5,3,"gFa1YMEJFag,UEvVksP91kg,rSJ8QZWBegU,nRcovJn9xH..."
2,rSJ8QZWBegU,TimeGem,1135.0,Entertainment,95,356,4.31,13,1,"gFa1YMEJFag,UEvVksP91kg,3TYqkBJ9YRk,nRcovJn9xH..."
3,nRcovJn9xHg,wooochacha,1135.0,Entertainment,118,1115,2.23,57,73,"gFa1YMEJFag,UEvVksP91kg,3TYqkBJ9YRk,ZTopArY7Nb..."
4,UEvVksP91kg,johnx113,1135.0,Entertainment,83,281,2.67,9,16,"QuRYeRnAuXM,3TYqkBJ9YRk,0TZqX5MbXMA,rSJ8QZWBeg..."
...,...,...,...,...,...,...,...,...,...,...
4061,esCvu46qDaA,RSMFD,863.0,Entertainment,63,116929,4.84,182,222,"vOskZNJJII8,q3qdBVDZrmE,mLDLe024T_I,bhLbFGVduT..."
4062,kOZ8bRAO7YQ,RockstarGames,0.0,UNA,63,199361,4.79,1256,2410,
4063,GSsVZcKHues,GTASite,1024.0,Entertainment,123,486752,4.86,1098,1764,"vOskZNJJII8,_X5nHLOiAVo,cNION6wGuso,5-reBn0gUk..."
4064,foKRqJGcbPQ,scrambledeggsTV,1100.0,Entertainment,136,13115,4.45,33,37,"_X5nHLOiAVo,5-reBn0gUkg,e8bEzU2Tx7c,e4yx1s-l6f..."
4065,-CYhSNHbeC8,rehab07,771.0,Entertainment,186,103556,4.30,277,220,"EOj-iWkcJPU,pg3j4IBMRZE,2GHiAEeFQs0,e4yx1s-l6f..."

In [79]:
data.describe().toPandas()

,summary,Video ID,Video Uploader,Interval between YouTube Establishment and Video Upload,Video Category,Video Length,Number of Views,Rating on the Video,Number of Ratings,Number of Comments,Related Video IDs
0,count,4066,4066,4066,4066,4066,4066,4066,4066,4066,4066
1,mean,None,1.5376751983333333E9,956.7144613871127,None,232.90629611411705,194695.10944417116,3.7562592228234193,588.5696015740285,534.873831775701,None
2,stddev,None,3.7656233115157094E9,214.1813221148062,None,219.47567245418742,1488250.2854682275,1.6787591038040413,3767.8937760638273,5032.528303622258,None
3,min,-08YZF87OBQ,000ILoveNaruto000,0.0,UNA,1,0,0.0,0,0,
4,max,zzlDKaXAIgE,zzzzzzzzap,1136.0,Travel & Events,5202,65341925,5.0,122129,259683,"zzlDKaXAIgE,e_Oun_GTKDo,4ira1eUOQGY,RWS45QqP1l..."

In [80]:
null_count=data.filter(data["Related Video IDs"].isNull()).count()
null_count

0

In [81]:
data.select('Related Video IDs').toPandas()

                                      Related Video IDs
0     nRcovJn9xHg,3TYqkBJ9YRk,rSJ8QZWBegU,0TZqX5MbXM...
1     gFa1YMEJFag,UEvVksP91kg,rSJ8QZWBegU,nRcovJn9xH...
2     gFa1YMEJFag,UEvVksP91kg,3TYqkBJ9YRk,nRcovJn9xH...
3     gFa1YMEJFag,UEvVksP91kg,3TYqkBJ9YRk,ZTopArY7Nb...
4     QuRYeRnAuXM,3TYqkBJ9YRk,0TZqX5MbXMA,rSJ8QZWBeg...
...                                                 ...
4061  vOskZNJJII8,q3qdBVDZrmE,mLDLe024T_I,bhLbFGVduT...
4062
4063  vOskZNJJII8,_X5nHLOiAVo,cNION6wGuso,5-reBn0gUk...
4064  _X5nHLOiAVo,5-reBn0gUkg,e8bEzU2Tx7c,e4yx1s-l6f...
4065  EOj-iWkcJPU,pg3j4IBMRZE,2GHiAEeFQs0,e4yx1s-l6f...

[4066 rows x 1 columns]

In [92]:
data[data['Related Video IDs']==''].count()

827

In [101]:
# Replace empty strings with null in 'Related Video IDs'
data_cleaned = data.withColumn(
    'Related Video IDs',
    when(col('Related Video IDs') == '', None).otherwise(col('Related Video IDs'))
)

In [102]:
data_cleaned[data_cleaned['Related Video IDs']==''].count()

0

In [103]:
data=data_cleaned

In [104]:
data.count()

4066

In [105]:
data.dropna()

DataFrame[Video ID: string, Video Uploader: string, Interval between YouTube Establishment and Video Upload: double, Video Category: string, Video Length: int, Number of Views: int, Rating on the Video: double, Number of Ratings: int, Number of Comments: int, Related Video IDs: string]

In [106]:
data.count()

4066

In [117]:
data = data.filter(col('Related Video IDs').isNotNull())

In [118]:
data.count()

3239

In [119]:
data.toPandas()

,Video ID,Video Uploader,Interval between YouTube Establishment and Video Upload,Video Category,Video Length,Number of Views,Rating on the Video,Number of Ratings,Number of Comments,Related Video IDs
0,QuRYeRnAuXM,EvilSquirrelPictures,1135.0,Pets & Animals,252,1075,4.96,46,86,"nRcovJn9xHg,3TYqkBJ9YRk,rSJ8QZWBegU,0TZqX5MbXM..."
1,3TYqkBJ9YRk,hggh22,1135.0,Comedy,169,228,5.00,5,3,"gFa1YMEJFag,UEvVksP91kg,rSJ8QZWBegU,nRcovJn9xH..."
2,rSJ8QZWBegU,TimeGem,1135.0,Entertainment,95,356,4.31,13,1,"gFa1YMEJFag,UEvVksP91kg,3TYqkBJ9YRk,nRcovJn9xH..."
3,nRcovJn9xHg,wooochacha,1135.0,Entertainment,118,1115,2.23,57,73,"gFa1YMEJFag,UEvVksP91kg,3TYqkBJ9YRk,ZTopArY7Nb..."
4,UEvVksP91kg,johnx113,1135.0,Entertainment,83,281,2.67,9,16,"QuRYeRnAuXM,3TYqkBJ9YRk,0TZqX5MbXMA,rSJ8QZWBeg..."
...,...,...,...,...,...,...,...,...,...,...
3234,S95602a7cFE,mattCTB,1045.0,Entertainment,87,39885,4.51,63,131,"bLAP45F4UCw,URIaUbRjIrU,x2TUkfeO-gM,Ydm5IedLYS..."
3235,esCvu46qDaA,RSMFD,863.0,Entertainment,63,116929,4.84,182,222,"vOskZNJJII8,q3qdBVDZrmE,mLDLe024T_I,bhLbFGVduT..."
3236,GSsVZcKHues,GTASite,1024.0,Entertainment,123,486752,4.86,1098,1764,"vOskZNJJII8,_X5nHLOiAVo,cNION6wGuso,5-reBn0gUk..."
3237,foKRqJGcbPQ,scrambledeggsTV,1100.0,Entertainment,136,13115,4.45,33,37,"_X5nHLOiAVo,5-reBn0gUkg,e8bEzU2Tx7c,e4yx1s-l6f..."
3238,-CYhSNHbeC8,rehab07,771.0,Entertainment,186,103556,4.30,277,220,"EOj-iWkcJPU,pg3j4IBMRZE,2GHiAEeFQs0,e4yx1s-l6f..."

In [120]:
# Define the directory path to save the CSV files
output_directory = 'D:/OneDrive - TVS Motor Company Ltd/Desktop/TRAINING/Day26/cleaned_data/'

# Export the DataFrame to a CSV file
data.write.csv(output_directory, header=True, mode='overwrite')

Py4JJavaError: An error occurred while calling o659.csv.
: java.lang.RuntimeException: java.io.FileNotFoundException: java.io.FileNotFoundException: HADOOP_HOME and hadoop.home.dir are unset. -see https://wiki.apache.org/hadoop/WindowsProblems
	at org.apache.hadoop.util.Shell.getWinUtilsPath(Shell.java:735)
	at org.apache.hadoop.util.Shell.getSetPermissionCommand(Shell.java:270)
	at org.apache.hadoop.util.Shell.getSetPermissionCommand(Shell.java:286)
	at org.apache.hadoop.fs.RawLocalFileSystem.setPermission(RawLocalFileSystem.java:978)
	at org.apache.hadoop.fs.RawLocalFileSystem.mkOneDirWithMode(RawLocalFileSystem.java:660)
	at org.apache.hadoop.fs.RawLocalFileSystem.mkdirsWithOptionalPermission(RawLocalFileSystem.java:700)
	at org.apache.hadoop.fs.RawLocalFileSystem.mkdirs(RawLocalFileSystem.java:672)
	at org.apache.hadoop.fs.RawLocalFileSystem.mkdirsWithOptionalPermission(RawLocalFileSystem.java:699)
	at org.apache.hadoop.fs.RawLocalFileSystem.mkdirs(RawLocalFileSystem.java:672)
	at org.apache.hadoop.fs.RawLocalFileSystem.mkdirsWithOptionalPermission(RawLocalFileSystem.java:699)
	at org.apache.hadoop.fs.RawLocalFileSystem.mkdirs(RawLocalFileSystem.java:672)
	at org.apache.hadoop.fs.ChecksumFileSystem.mkdirs(ChecksumFileSystem.java:788)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.setupJob(FileOutputCommitter.java:356)
	at org.apache.spark.internal.io.HadoopMapReduceCommitProtocol.setupJob(HadoopMapReduceCommitProtocol.scala:188)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.writeAndCommit(FileFormatWriter.scala:269)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeWrite(FileFormatWriter.scala:304)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:190)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:190)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:113)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:111)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.executeCollect(commands.scala:125)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:142)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:859)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:388)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:361)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:240)
	at org.apache.spark.sql.DataFrameWriter.csv(DataFrameWriter.scala:850)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: java.io.FileNotFoundException: HADOOP_HOME and hadoop.home.dir are unset. -see https://wiki.apache.org/hadoop/WindowsProblems
	at org.apache.hadoop.util.Shell.fileNotFoundException(Shell.java:547)
	at org.apache.hadoop.util.Shell.getHadoopHomeDir(Shell.java:568)
	at org.apache.hadoop.util.Shell.getQualifiedBin(Shell.java:591)
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:688)
	at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:79)
	at org.apache.hadoop.conf.Configuration.getTimeDurationHelper(Configuration.java:1907)
	at org.apache.hadoop.conf.Configuration.getTimeDuration(Configuration.java:1867)
	at org.apache.hadoop.conf.Configuration.getTimeDuration(Configuration.java:1840)
	at org.apache.hadoop.util.ShutdownHookManager.getShutdownTimeout(ShutdownHookManager.java:183)
	at org.apache.hadoop.util.ShutdownHookManager$HookEntry.<init>(ShutdownHookManager.java:207)
	at org.apache.hadoop.util.ShutdownHookManager.addShutdownHook(ShutdownHookManager.java:304)
	at org.apache.spark.util.SparkShutdownHookManager.install(ShutdownHookManager.scala:181)
	at org.apache.spark.util.ShutdownHookManager$.shutdownHooks$lzycompute(ShutdownHookManager.scala:50)
	at org.apache.spark.util.ShutdownHookManager$.shutdownHooks(ShutdownHookManager.scala:48)
	at org.apache.spark.util.ShutdownHookManager$.addShutdownHook(ShutdownHookManager.scala:153)
	at org.apache.spark.util.ShutdownHookManager$.<init>(ShutdownHookManager.scala:58)
	at org.apache.spark.util.ShutdownHookManager$.<clinit>(ShutdownHookManager.scala)
	at org.apache.spark.util.Utils$.createTempDir(Utils.scala:242)
	at org.apache.spark.util.SparkFileUtils.createTempDir(SparkFileUtils.scala:103)
	at org.apache.spark.util.SparkFileUtils.createTempDir$(SparkFileUtils.scala:102)
	at org.apache.spark.util.Utils$.createTempDir(Utils.scala:94)
	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:372)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:964)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.io.FileNotFoundException: HADOOP_HOME and hadoop.home.dir are unset.
	at org.apache.hadoop.util.Shell.checkHadoopHomeInner(Shell.java:467)
	at org.apache.hadoop.util.Shell.checkHadoopHome(Shell.java:438)
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:515)
	... 25 more